"""Add column last_name to User model

Revision ID: 415dec1093ea
Revises: 
Create Date: 2023-03-21 21:21:41.476620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415dec1093ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
