"""Add column last_name to User model

Revision ID: 46ccee8753ff
Revises: 415dec1093ea
Create Date: 2023-03-21 21:27:49.113734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ccee8753ff'
down_revision = '415dec1093ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
